baseURL = 'https://example.org/'
title = '东水的blog'
theme = 'reimu'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true
[markup.highlight]
guessSyntax = true
noClasses = false
[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]
[taxonomies]
category = "categories"
tag = "tags"
[markup.goldmark.renderer]
unsafe = true